import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const SECTIONS = [
  {
    title: "1. Information We Collect",
    body: `We collect information you provide directly (name, email, password, identity documents for KYC), information generated by your use of the platform (listings viewed, offers made, escrow transactions), and technical data (IP address, browser type, device identifiers).`,
  },
  {
    title: "2. How We Use Your Information",
    body: `We use your data to: operate and improve the platform; verify your identity (KYC); process transactions and escrow; send notifications about your activity; comply with legal obligations; and prevent fraud and abuse.`,
  },
  {
    title: "3. Identity Verification (KYC)",
    body: `To make offers and initiate escrow, you must complete identity verification. Documents you upload (passport, national ID) are stored securely and used solely for verification purposes. Verified status is shared with counterparties in a transaction to establish trust, but raw document files are not.`,
  },
  {
    title: "4. Sharing Your Information",
    body: `We do not sell your personal data. We share data with: (a) counterparties in a transaction (name, KYC status); (b) service providers who help us operate the platform under strict confidentiality; (c) law enforcement or regulators when required by law.`,
  },
  {
    title: "5. Data Retention",
    body: `We retain account data for as long as your account is active and for 7 years after closure to comply with financial record-keeping obligations. Identity documents are retained for 5 years post-transaction to meet anti-money laundering requirements.`,
  },
  {
    title: "6. Your Rights",
    body: `Depending on your jurisdiction you may have the right to: access the data we hold about you; correct inaccurate data; request deletion (subject to legal retention obligations); object to processing; and data portability. To exercise any right, contact us at privacy@kunda.gm.`,
  },
  {
    title: "7. Security",
    body: `We use industry-standard encryption (TLS in transit, AES-256 at rest), access controls, and regular security reviews. No system is perfectly secure — if you believe your account has been compromised, contact us immediately.`,
  },
  {
    title: "8. Cookies",
    body: `We use essential cookies for authentication and session management. We do not use advertising or tracking cookies. You can disable cookies in your browser settings but some features may not work correctly.`,
  },
  {
    title: "9. Changes to This Policy",
    body: `We may update this policy from time to time. We'll notify registered users by email of material changes at least 14 days before they take effect.`,
  },
  {
    title: "10. Contact",
    body: `For privacy questions, contact our Data Protection Officer at privacy@kunda.gm or write to Kunda Properties Ltd, Banjul, The Gambia.`,
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />
      <main className="pt-20">
        <section className="bg-kunda-950 text-white py-16 px-4 text-center">
          <h1 className="font-display text-4xl font-bold mb-3">Privacy Policy</h1>
          <p className="text-white/60">Last updated: July 2026</p>
        </section>
        <section className="py-16 px-4">
          <div className="container mx-auto max-w-3xl">
            <p className="text-gray-600 leading-relaxed mb-10">
              This Privacy Policy explains how Kunda Properties ("Kunda", "we", "us") collects, uses, and protects personal information when you use our platform. By using Kunda, you agree to this policy.
            </p>
            <div className="space-y-8">
              {SECTIONS.map(({ title, body }) => (
                <div key={title}>
                  <h2 className="font-display text-xl font-bold text-gray-900 mb-3">{title}</h2>
                  <p className="text-gray-600 leading-relaxed">{body}</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
