import type { PropertyListing } from "@/types/property";

export const propertySeedData: PropertyListing[] = [
  {
    agent: {
      agency: "Kunda Premier",
      languages: ["English", "Wolof"],
      name: "Awa Ceesay",
      phone: "+220 388 1200",
      responseTime: "Usually replies within 20 minutes",
      title: "Senior property advisor",
      whatsapp: "+2203881200",
      yearsExperience: 8,
    },
    bathrooms: 3,
    bedrooms: 4,
    completion: "Move-in ready",
    currency: "USD",
    description:
      "A bright coastal home with a shaded courtyard, private generator backup, and a flexible ground-floor suite for visiting family or remote work. The property is already packaged for escrow with title copies, survey plan, and seller documentation ready for review.",
    enquiryCount: 18,
    escrowReady: true,
    featured: true,
    gallery: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
    ],
    headline: "Ocean-facing family villa with verified title pack",
    highlights: ["Ocean air", "Backup power", "Escrow ready"],
    id: "kg-001",
    location: "Cape Point, Bakau",
    price: 285000,
    publishedAt: "2026-03-19",
    region: "West Coast",
    sizeLabel: "420 sqm",
    sizeSqm: 420,
    slug: "atlantic-view-villa",
    summary: "Four-bedroom villa minutes from the beach and diaspora-friendly schools.",
    title: "Atlantic View Villa",
    type: "house",
    verified: true,
  },
  {
    agent: {
      agency: "Kunda Premier",
      languages: ["English", "French"],
      name: "Muhammed Jatta",
      phone: "+220 733 4455",
      responseTime: "Replies same day",
      title: "Investment sales lead",
      whatsapp: "+2207334455",
      yearsExperience: 6,
    },
    bathrooms: 2,
    bedrooms: 3,
    completion: "Ready in 30 days",
    currency: "USD",
    description:
      "A furnished apartment cluster close to Bijilo's tourism strip with strong short-stay rental demand. The current owner is selling the unit with management handover notes and a tenant-ready furnishing package.",
    enquiryCount: 11,
    escrowReady: true,
    featured: true,
    gallery: [
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1460317442991-0ec209397118?auto=format&fit=crop&w=1200&q=80",
    ],
    headline: "Diaspora-friendly apartment close to beaches and rental demand",
    highlights: ["Rental ready", "Managed building", "Airport corridor"],
    id: "kg-002",
    location: "Bijilo, Senegambia strip",
    price: 168000,
    publishedAt: "2026-03-28",
    region: "West Coast",
    sizeLabel: "164 sqm",
    sizeSqm: 164,
    slug: "bijilo-gardens-apartment",
    summary: "Modern three-bedroom apartment with concierge services and rental upside.",
    title: "Bijilo Gardens Apartment",
    type: "apartment",
    verified: true,
  },
  {
    agent: {
      agency: "North Shore Land Desk",
      languages: ["English", "Wolof"],
      name: "Mariatou Sonko",
      phone: "+220 321 8090",
      responseTime: "Usually replies within 1 hour",
      title: "Land acquisition advisor",
      whatsapp: "+2203218090",
      yearsExperience: 10,
    },
    bathrooms: 0,
    bedrooms: 0,
    completion: "Build-ready after survey transfer",
    currency: "USD",
    description:
      "A rectangular lagoon-side parcel with road access, a clear chain-of-ownership file, and room for a villa compound or serviced apartments. The title verification queue has already passed manual land registry review for the seller.",
    enquiryCount: 9,
    escrowReady: false,
    featured: false,
    gallery: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80",
    ],
    headline: "Titled coastal land with survey file already reviewed",
    highlights: ["Lagoon access", "Survey complete", "Development parcel"],
    id: "kg-003",
    location: "Tanji lagoon edge",
    lotSizeSqm: 900,
    price: 54000,
    publishedAt: "2026-02-14",
    region: "West Coast",
    sizeLabel: "900 sqm",
    slug: "tanji-lagoon-land",
    summary: "Large titled land parcel suited to a compound home or serviced apartments.",
    title: "Tanji Lagoon Land",
    type: "land",
    verified: true,
  },
  {
    agent: {
      agency: "Kunda Commercial",
      languages: ["English", "Mandinka"],
      name: "Buba Sanyang",
      phone: "+220 709 5501",
      responseTime: "Replies within 45 minutes",
      title: "Commercial acquisitions specialist",
      whatsapp: "+2207095501",
      yearsExperience: 12,
    },
    bathrooms: 4,
    bedrooms: 0,
    completion: "Income producing",
    currency: "USD",
    description:
      "Street-facing mixed-use property with retail frontage on the ground floor and finished office suites above. Strong candidate for diaspora investors looking for cash flow, with ledger history and utility records prepared for diligence.",
    enquiryCount: 13,
    escrowReady: true,
    featured: true,
    gallery: [
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366412874-3415097a27e7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80",
    ],
    headline: "Retail and office income property in a high-footfall corridor",
    highlights: ["Income producing", "Prime frontage", "Verified books"],
    id: "kg-004",
    location: "Serekunda market corridor",
    price: 215000,
    publishedAt: "2026-03-10",
    region: "Kanifing",
    sizeLabel: "310 sqm",
    sizeSqm: 310,
    slug: "serekunda-commerce-hub",
    summary: "Commercial building with retail frontage and active lease income.",
    title: "Serekunda Commerce Hub",
    type: "commercial",
    verified: true,
  },
  {
    agent: {
      agency: "Kunda Premier",
      languages: ["English", "Wolof", "French"],
      name: "Fatou Bensouda",
      phone: "+220 775 2234",
      responseTime: "Usually replies within 30 minutes",
      title: "Luxury home specialist",
      whatsapp: "+2207752234",
      yearsExperience: 9,
    },
    bathrooms: 4,
    bedrooms: 5,
    completion: "Move-in ready",
    currency: "USD",
    description:
      "Spacious courtyard home in a quiet Fajara pocket, designed for multi-generational living with two lounge areas and a detached guest suite. Utility upgrades and water storage are already installed, making it practical for owners living abroad.",
    enquiryCount: 7,
    escrowReady: false,
    featured: false,
    gallery: [
      "https://images.unsplash.com/photo-1576941089067-2de3c901e126?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
    ],
    headline: "Elegant courtyard home with guest suite and resilient utilities",
    highlights: ["Quiet street", "Guest suite", "Water reserve"],
    id: "kg-005",
    location: "Fajara diplomatic quarter",
    price: 380000,
    publishedAt: "2026-01-30",
    region: "Kanifing",
    sizeLabel: "510 sqm",
    sizeSqm: 510,
    slug: "fajara-courtyard-home",
    summary: "Large family house with courtyard entertaining space and a guest suite.",
    title: "Fajara Courtyard Home",
    type: "house",
    verified: true,
  },
  {
    agent: {
      agency: "Coastline Residences",
      languages: ["English"],
      name: "Lamin Jarju",
      phone: "+220 260 9900",
      responseTime: "Replies same day",
      title: "Residential advisor",
      whatsapp: "+2202609900",
      yearsExperience: 5,
    },
    bathrooms: 2,
    bedrooms: 2,
    completion: "Ready in 45 days",
    currency: "USD",
    description:
      "A bright apartment on Brufut ridge with cross-ventilation, gated parking, and easy access to the highway. Strong option for buyers who want a lower-maintenance home with predictable running costs.",
    enquiryCount: 5,
    escrowReady: true,
    featured: false,
    gallery: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
    ],
    headline: "Gated two-bedroom apartment with low-maintenance ownership profile",
    highlights: ["Gated parking", "Highway access", "Low maintenance"],
    id: "kg-006",
    location: "Brufut ridge",
    price: 132000,
    publishedAt: "2026-03-01",
    region: "West Coast",
    sizeLabel: "142 sqm",
    sizeSqm: 142,
    slug: "brufut-ridge-apartment",
    summary: "Well-finished apartment designed for lock-up-and-go living.",
    title: "Brufut Ridge Apartment",
    type: "apartment",
    verified: true,
  },
];

export function getAllProperties() {
  return propertySeedData;
}

export function getFeaturedProperties() {
  return propertySeedData.filter((property) => property.featured);
}

export function getPropertyBySlug(slug: string) {
  return propertySeedData.find((property) => property.slug === slug);
}

export const listingRegions = Array.from(
  new Set(propertySeedData.map((property) => property.region)),
);